---
title: "Exploring depensatory hidden markov models"
output:
  html_document:
    collapsed: no
    fig_caption: yes
    smooth_scroll: yes
    theme: cerulean
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggh4x) #for nicer facetting
library(here)
```

```{r read and filter data}
SR_data <- read.csv(here("data/salmon_productivity_compilation_may2023.csv")) |>
  select(-X)

stock_info <- read.csv(here('data','all_stocks_info_may2023.csv')) |>
  select(-X, -source, -url)

SR_data_filter <- filter(SR_data, !(stock %in% c("Andrew Creek-Chinook", 
                                                 "Alsek/Klukshu-Chinook",
                                                "Alsek-Klukshu-Chinook",
                                                "East Fork South Fork Salmon River-Chinook",
                                                "Entiat River-Chinook", 
                                                "Minam River-Chinook",
                                                "Coweeman River-Chinook", 
                                                "Misc. Nahatlatch-Sockeye"))) |>
  mutate(spawners = ifelse(spawners==0|recruits==0, spawners+1, spawners),
         recruits = ifelse(spawners==0|recruits==0, recruits+1, recruits)) |> #*why write both?
         mutate(logRS = log(recruits/spawners))
```

```{r fit data}
refit <- TRUE #toggle if you want

if(!("hmm_summary.csv"%in%list.files(here("outputs"))) | refit == TRUE){
  depensation_summary <- data.frame(NULL)

#SR_data_filter <- filter(SR_data_filter, stock %in% unique(SR_data_filter$stock)[1:2])
for(i in unique(SR_data_filter$stock)){ 
  sub_stock <- filter(SR_data_filter, stock == i) |>
      na.omit()
  
 hmm.fit <- rstan::stan(file = here("code/HMM/allee_hmm.stan"),  
                      data=list(N=nrow(sub_stock),
                              R_S=sub_stock$logRS,
                              S=sub_stock$spawners,
                              K=2,
                              pSmax_mean=max(sub_stock$spawners)*0.5,
                              pSmax_sig=max(sub_stock$spawners)*0.5), 
                      control = list(adapt_delta = 0.95,max_treedepth = 15), 
                      warmup = 200, 
                      chains = 4, 
                      iter = 800, 
                      thin = 1)
  
  params <- rstan::extract(hmm.fit)
  fit_summary <- as.data.frame(rstan::summary(hmm.fit)$summary)

  depensation_summary <- bind_rows(depensation_summary, 
                                   data.frame(species = unique(sub_stock$species),
                                              stock = unique(sub_stock$stock),
                                              log_a_med = median(params$log_a),
                                              log_a_Q1 = quantile(params$log_a,0.25),
                                              log_a_Q3 = quantile(params$log_a,0.75),
                                              gamma_med = median(params$gamma),
                                              gamma_Q1 = quantile(params$gamma,0.25),
                                              gamma_Q3 = quantile(params$gamma,0.75),
                                              w_med = median(params$w),
                                              w_Q1 = quantile(params$w,0.25),
                                              w_Q3 = quantile(params$w,0.75),
                                              max_Rhat = max(fit_summary$Rhat, na.rm = TRUE),
                                              mis_ess = min(fit_summary$ESS)))
}
  
write.csv(depensation_summary, here("outputs/hmm_summary.csv"))
} else{
  depensation_summary <- read.csv(here("outputs/hmm_summary.csv"))
}


```

# plot it

```{r plot parms}
depensation_summary <- arrange(depensation_summary, species, stock) |>
  mutate(species = as.factor(species),
         stock = as.factor(stock), 
         pop = as.factor(row_number()))

ggplot(depensation_summary) +
  geom_pointrange(aes(x = pop, y = w_med, ymin = w_LCI, ymax = w_UCI, 
                      color = species)) +
  theme_minimal() +
  labs(x = "population", y= "w parameter quantiles") +
  theme(axis.text.x = element_blank())
  
```